### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Koitharu** [vshelest/ChuckNorrisJokes#1]
https://github.com/vshelest/ChuckNorrisJokes/blob/e560d09cd0f7e922fb58a7a44aa6d94659a50620/app/src/main/java/com/training/chucknorrisjokessearch/domain/usecase/implementation/JokesUseCaseImpl.kt#L21-L23

Наверное, правильнее было бы `getJokes` сделать suspend и возвращать сразу результат, а StateFlow использовать во ViewModel-е

https://github.com/vshelest/ChuckNorrisJokes/blob/e560d09cd0f7e922fb58a7a44aa6d94659a50620/app/src/main/java/com/training/chucknorrisjokessearch/presentation/activity/MainActivity.kt#L41-L47

Тут стоит просто вызывать функцию у ViewModel, которая будет обновлять `searchStringFlow`

https://github.com/vshelest/ChuckNorrisJokes/blob/e560d09cd0f7e922fb58a7a44aa6d94659a50620/app/src/main/java/com/training/chucknorrisjokessearch/presentation/viewmodel/implementation/JokesViewModelImpl.kt#L28

Лучше бы сделать так:
- `debounce()`
- `mapLatest()` -- тут загружать данные из сети
- `onEach()` -- сохраняем результат, `_jokesFlow.value = it`

https://github.com/vshelest/ChuckNorrisJokes/blob/e560d09cd0f7e922fb58a7a44aa6d94659a50620/app/src/main/java/com/training/chucknorrisjokessearch/presentation/viewmodel/implementation/JokesViewModelImpl.kt#L37

`Dispatchers.IO` тут нигде использовать не нужно. Работу с сетью retrofit (а, точнее, okhttp) сам выполняет в нужном потоке, а для всего остального лучше подходит `Dispatchers.Default`. Ну и `viewModelScope` использовать нужно

**Comment by vshelest** [comment]
Дуже дякую за Review та уточнення. Додав ці зміни
